# Generated by Django 4.2.13 on 2025-05-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_health_app', '0004_alter_plantimage_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plantimage',
            table=None,
        ),
    ]
