# Generated by Django 4.2.13 on 2025-05-25 14:00

from django.db import migrations, models
import plant_health_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_health_app', '0005_alter_plantimage_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=plant_health_app.models.get_image_path)),
                ('disease', models.CharField(blank=True, max_length=100)),
                ('plant_type', models.CharField(blank=True, max_length=100)),
                ('dataset_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
