# Generated by Django 4.2 on 2025-10-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_health_app", "0010_question_designated_expert_question_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseaselibrary",
            name="plant_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
