# Generated by Django 4.2 on 2025-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_health_app", "0013_blogcomment_blogpost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Lý do từ chối bài viết", null=True
            ),
        ),
    ]
