# Generated by Django 4.2 on 2025-12-08 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plant_health_app", "0014_blogpost_rejection_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantimage",
            name="plant",
        ),
        migrations.RemoveField(
            model_name="plantimage",
            name="user",
        ),
        migrations.DeleteModel(
            name="PlantModel",
        ),
        migrations.DeleteModel(
            name="PlantImage",
        ),
    ]
