# Generated by Django 4.2 on 2025-12-08 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plant_health_app",
            "0015_remove_plantimage_plant_remove_plantimage_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionhistory",
            name="plant",
        ),
        migrations.DeleteModel(
            name="Plant",
        ),
    ]
