# Generated by Django 4.2 on 2025-12-08 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plant_health_app", "0016_remove_predictionhistory_plant_delete_plant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="predictionhistory",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Lịch sử dự đoán",
                "verbose_name_plural": "Lịch sử dự đoán",
            },
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ duyệt"),
                    ("ACCEPTED", "Đã duyệt"),
                    ("REJECTED", "Đã từ chối"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Trạng thái kiểm duyệt của ảnh",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="contribution_type",
            field=models.CharField(
                choices=[
                    ("CONSULTING", "Chỉ xem (Hỏi đường)"),
                    ("CONTRIBUTING", "Đóng góp cho AI"),
                ],
                default="CONSULTING",
                help_text="Mục đích upload ảnh: Chỉ xem hay đóng góp cho AI",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Lý do từ chối (nếu approval_status = REJECTED)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="Thời gian kiểm duyệt", null=True
            ),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin đã kiểm duyệt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_predictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="user_agreed_with_ai",
            field=models.BooleanField(
                default=False,
                help_text="User đồng ý với dự đoán của AI hay tự sửa nhãn",
            ),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="user_confirmed_disease",
            field=models.CharField(
                blank=True,
                help_text="Nhãn bệnh do user xác nhận (có thể khác với AI prediction)",
                max_length=100,
                null=True,
            ),
        ),
    ]
