# Generated by Django 4.2 on 2026-01-16 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "plant_health_app",
            "0018_blogcomment_deleted_at_blogcomment_deleted_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("remove_duplicates", models.BooleanField(default=True)),
                ("remove_blurry", models.BooleanField(default=True)),
                ("blur_threshold", models.FloatField(default=100.0)),
                ("total_images", models.IntegerField(default=0)),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREPARING", "Đang chuẩn bị"),
                            ("READY", "Sẵn sàng"),
                            ("USED", "Đã sử dụng"),
                        ],
                        default="PREPARING",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Dataset",
                "verbose_name_plural": "Training Datasets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("PLANT_TYPE", "Plant Type Classification"),
                            ("DISEASE", "Disease Classification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("architecture", models.CharField(max_length=100)),
                ("optimizer", models.CharField(max_length=50)),
                ("file_path", models.CharField(max_length=500)),
                ("training_accuracy", models.FloatField(blank=True, null=True)),
                ("validation_accuracy", models.FloatField(blank=True, null=True)),
                ("training_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plant_health_app.trainingdataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Version",
                "verbose_name_plural": "Model Versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingDatasetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_duplicate", models.BooleanField(default=False)),
                ("is_blurry", models.BooleanField(default=False)),
                ("blur_score", models.FloatField(blank=True, null=True)),
                ("included", models.BooleanField(default=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="plant_health_app.trainingdataset",
                    ),
                ),
                (
                    "prediction_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_health_app.predictionhistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset Image",
                "verbose_name_plural": "Dataset Images",
                "unique_together": {("dataset", "prediction_history")},
            },
        ),
    ]
