# Generated by Django 4.2 on 2026-01-19 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plant_health_app", "0019_trainingdataset_modelversion_trainingdatasetimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tên phiên bản model", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "plant_type",
                    models.CharField(
                        db_index=True,
                        help_text="Loại cây (Tomato, Potato, Apple, Cherry, Corn, Grape, Peach, Pepper, Strawberry)",
                        max_length=100,
                    ),
                ),
                (
                    "architecture",
                    models.CharField(default="EfficientNet-B0", max_length=100),
                ),
                ("optimizer", models.CharField(max_length=50)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Đường dẫn file .pth (VD: models/tomato_disease_v1.pth)",
                        max_length=500,
                    ),
                ),
                ("training_accuracy", models.FloatField(blank=True, null=True)),
                ("validation_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "num_classes",
                    models.IntegerField(
                        blank=True,
                        help_text="Số lượng bệnh cho loại cây này",
                        null=True,
                    ),
                ),
                ("training_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Model đang được sử dụng cho loại cây này",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plant_health_app.trainingdataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Model",
                "verbose_name_plural": "Disease Models",
                "ordering": ["plant_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlantTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tên phiên bản model (VD: EfficientNet-B0 AdamW v1)",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "architecture",
                    models.CharField(default="EfficientNet-B0", max_length=100),
                ),
                ("optimizer", models.CharField(max_length=50)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Đường dẫn file .pth (VD: models/plant_type_v1.pth)",
                        max_length=500,
                    ),
                ),
                ("training_accuracy", models.FloatField(blank=True, null=True)),
                ("validation_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "num_classes",
                    models.IntegerField(
                        default=9, help_text="Số lượng loại cây (mặc định 9)"
                    ),
                ),
                ("training_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Model đang được sử dụng cho web"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plant_health_app.trainingdataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Type Model",
                "verbose_name_plural": "Plant Type Models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RetrainJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("PLANT_TYPE", "Retrain Plant Type Model"),
                            ("DISEASE", "Retrain Disease Model"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plant_type",
                    models.CharField(
                        blank=True,
                        help_text="Chỉ dùng cho DISEASE jobs",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("optimizer", models.CharField(max_length=50)),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ train"),
                            ("RUNNING", "Đang train"),
                            ("COMPLETED", "Hoàn thành"),
                            ("FAILED", "Thất bại"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("final_training_accuracy", models.FloatField(blank=True, null=True)),
                ("final_validation_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "training_metrics",
                    models.TextField(blank=True, help_text="JSON hoặc text metrics"),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plant_health_app.trainingdataset",
                    ),
                ),
                (
                    "disease_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plant_health_app.diseasemodel",
                    ),
                ),
                (
                    "new_disease_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrain_jobs_created",
                        to="plant_health_app.diseasemodel",
                    ),
                ),
                (
                    "new_plant_type_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrain_jobs_created",
                        to="plant_health_app.planttypemodel",
                    ),
                ),
                (
                    "plant_type_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plant_health_app.planttypemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retrain Job",
                "verbose_name_plural": "Retrain Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ModelVersion",
        ),
        migrations.AddIndex(
            model_name="diseasemodel",
            index=models.Index(
                fields=["plant_type", "is_default"],
                name="plant_healt_plant_t_f0a9b6_idx",
            ),
        ),
    ]
