# Generated by Django 4.2 on 2026-01-19 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plant_health_app", "0020_diseasemodel_planttypemodel_retrainjob_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RetrainJob",
        ),
    ]
