# Generated by Django 4.2 on 2026-01-20 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plant_health_app", "0022_trainingdataset_dataset_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ xử lý"),
                            ("PROCESSING", "Đang xử lý"),
                            ("COMPLETED", "Hoàn thành"),
                            ("FAILED", "Thất bại"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=200)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("total_images", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plant_health_app.trainingdataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exporttask",
            index=models.Index(
                fields=["status", "created_at"], name="plant_healt_status_f499b9_idx"
            ),
        ),
    ]
