# Generated by Django 4.2 on 2026-05-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plant_health_app",
            "0023_exporttask_exporttask_plant_healt_status_f499b9_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionhistory",
            name="cropped_image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="plant_images/cropped/"
            ),
        ),
        migrations.AddField(
            model_name="predictionhistory",
            name="segment_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
