# Generated by Django 4.2 on 2026-05-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_health_app", "0025_segmentation_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentationmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
