# Generated by Django 4.2 on 2026-05-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_health_app", "0026_alter_segmentationmodel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasemodel",
            name="label_group",
            field=models.CharField(
                blank=True,
                help_text="Ví dụ: Potato_3, Potato_7, Apple",
                max_length=100,
                null=True,
            ),
        ),
    ]
