# Generated by Django 4.2 on 2026-06-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_health_app", "0027_diseasemodel_label_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionhistory",
            name="inference_latency",
            field=models.FloatField(
                blank=True,
                help_text="Thời gian suy luận toàn trình đo bằng giây (End-to-End Inference Latency)",
                null=True,
            ),
        ),
    ]
